apiVersion: v1
kind: Pod
metadata:
  name: javawebapppods1
  labels: 
   app: javawebapps1
  namespace: flipkart-ns 
spec:
  containers:
  - name: javawebappcontainer1
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
  namespace: flipkart-ns
spec:
  type: ClusterIP
  selector:
     app: javawebapps1
  ports:
  - port: 80
    targetPort: 8080