apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  namespace: flipkart-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: mavenwebapps
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapps
    spec:
      containers:
      - name: mavenwebappcontainer
        image: dockerhandson/maven-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: flipkart-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapps
  ports:
  - port: 80
    targetPort: 8080
