apiVersion: v1
kind: Namespace
metadata:
  name: testns
---
#Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata: 
  name: testns-qs-quota
  namespace: testns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pod: "1"
---
#Limit Range
apiVersion: v1
kind: LimitRange
metadata:
  name: testns-limit-range
  namespace: testns
spec: 
  limits:
  - default: 
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 250Mi
    type: Container           

