apiVersion: v1
kind: Pod
metadata:
  name:  javawebapppods
  namespace: flipkart-ns
  labels:
    app: javawebapp 
spec:
  containers:
  - name: javawebappcontainer1
    image: dockerhandson/java-web-app:1
	  ports:
	  - containerPort: 8080
  - name: javawebappcontainer2
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8081