apiVersion: v1
kind: Pod
metadata:
  name: javawebapppods
  labels: 
   app: javawebapps
  namespace: flipkart-ns 
spec:
  containers:
  - name: javawebappcontainer
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8080
---
apiversion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: flipkart-ns
spec:
  selector:
    app: javawebapps
  ports:
  - port: 80
    targetPort: 8080
    