apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pythonappds
  namespace: flipkart-ns
spec:
  selector:
    matchLabels:
      app: pythonflaskapp
  template:
    metadata:
      name: pythonflaskapppod
      labels:
        app: pythonflaskapp
    spec:
      containers:
      - name: pythonflaskappcontainer
        image: dockerhandson/python-flask-app:1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pythonflaskappsvc
  namespace: flipkart-ns
spec:
  type: NodePort
  selector:
    app: pythonflaskapp
  ports:
  - port: 80
    targetPort: 5000
