apiVersion: v1
kind: Namespace
metadata:
  name: testns1
---
#Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: testns-qs-quota
  namespace: testns1
spec:
  hard:
    requests.cpu: "0.25"
    requests.memory: 256Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: 1
---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: testns-limit-range
  namespace: testns1
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container